### ISSUE TITLE
Azure deployment is now fully supported in doccano

### ISSUE THREAD

**Issue by c-w** [aribornstein/Doccano4Azure#1]
Note that doccano now supports Azure deployment in its master branch: [documentation](https://github.com/chakki-works/doccano#azure), [Dockerfile](https://github.com/chakki-works/doccano/blob/master/Dockerfile), [ARM template](https://github.com/chakki-works/doccano/blob/master/azuredeploy.json) so perhaps this repository can be archived?

**Comment by aribornstein** [comment]
sure
